---
validators:
- validator: umeevaloper1wusrw8nzgs6d8d47xqej5xqttvsu2geftfgu5f
  moniker: Stakewolle.com | Auto-compound
- validator: umeevaloper16kukyg8l6qse6n2rq24qr6qd3ylgnnzmut8v3u
  moniker: Coinpayu
window: 20
networks:
  canon:
    rpc: https://canon-4.rpc.network.umee.cc:443
    grpc: tcp://canon-4.network.umee.cc:11000
  mainnet:
    rpc: http://umee.rpc.m.stavr.tech:10457
    grpc: umee-grpc.polkachu.com:13690
  local:
    rpc: http://localhost:26657
    grpc: http://localhost:9090
