---
validators:
# - validator: umeevaloper1hd4zwgmu2uax5pp43mqdnn09720qmvuqjenkr4
#   moniker: val-1
- validator: umeevaloper1y6xz2ggfc0pcsmyjlekh0j9pxh6hk87ymuzzdn
  moniker: test
# - validator: umeevaloper1flsa6pzsafkfx58qqh3vq66a8gtauecleq64nx
#   moniker: val-4
window: 20
networks:
  canon:
    rpc: https://canon-4.rpc.network.umee.cc:443
    grpc: tcp://canon-4.network.umee.cc:11000
  mainnet:
    rpc: http://umee.rpc.m.stavr.tech:10457
    grpc: umee-grpc.polkachu.com:13690
  local:
    rpc: http://localhost:26657
    grpc: http://localhost:9090
